export const INITIAL_CATEGORIES = [
  { id: "especiales", name: "Especiales", color: "pink" },
  { id: "codec", name: "CODEC", color: "blue" },
  { id: "aspirantes", name: "Aspirantes", color: "orange" },
  { id: "familia", name: "Familia", color: "red" },
  { id: "sj", name: "SJ", color: "purple" },
  { id: "pitables", name: "Pitables", color: "yellow" },
  { id: "abuelos", name: "Abuelos", color: "brown" },
  { id: "sr", name: "SR.", color: "indigo" },
  { id: "amigos", name: "Amigos", color: "teal" },
  { id: "unav", name: "UNAV", color: "green" },
  { id: "clase-uam", name: "Clase UAM", color: "blue" },
  { id: "novios", name: "Novios", color: "pink" },
  { id: "europea", name: "Europea", color: "orange" },
  { id: "gente-montalban", name: "Gente Montalbán", color: "purple" },
  { id: "primos", name: "Primos", color: "teal" },
  { id: "con-los-que-he-vivido", name: "Con los que he vivido", color: "indigo" },
  { id: "jara", name: "Jara", color: "green" }
];

export const INITIAL_PEOPLE = [
  // Especiales
  { name: "El Papa 🇻🇦", category: "especiales", prayers: [] },
  { name: "El Padre [Estatutos]", category: "especiales", prayers: [
    { id: "padre-1", text: "Estatutos", status: "active" },
    { id: "padre-2", text: "Viaje apostólico", status: "active" }
  ] },
  { name: "D. José Cobo", category: "especiales", prayers: [
    { id: "cobo-1", text: "Por su ministerio episcopal", status: "active" }
  ] },
  { name: "POR MI NUEVO ENCARGO", category: "especiales", prayers: [] },
  { name: "ESPAÑA 🇪🇸", category: "especiales", prayers: [] },
  { name: "Y LOS QUE VENDRÁN", category: "especiales", prayers: [] },

  // CODEC
  { name: "Alfonso Jiménez", category: "codec", prayers: [] },
  { name: "D. Santiago Díaz", category: "codec", prayers: [] },
  { name: "Pablo García", category: "codec", prayers: [] },
  { name: "Pablo Guijarro", category: "codec", prayers: [] },
  { name: "D. Cayetano Taberner", category: "codec", prayers: [] },
  { name: "D. Álex Gutiérrez de Caviedes", category: "codec", prayers: [] },
  { name: "Josemaría Muñoz", category: "codec", prayers: [] },
  { name: "Iñaki Losana", category: "codec", prayers: [] },
  { name: "Javier García Donate", category: "codec", prayers: [] },
  { name: "Gonzalo Halcón", category: "codec", prayers: [] },
  { name: "Fonfi", category: "codec", prayers: [] },
  { name: "Javi Arellano", category: "codec", prayers: [] },
  { name: "Manuel Uche Soria (Codec)", category: "codec", prayers: [] },
  { name: "Pablo Dolz del Castellar (Codec)", category: "codec", prayers: [] },
  { name: "Tomás Sangrador (Codec)", category: "codec", prayers: [] },
  { name: "Pablo Buerba (Codec)", category: "codec", prayers: [] },

  // Aspirantes
  { name: "Pablo Ortiz", category: "aspirantes", prayers: [] },
  { name: "Álvaro Farmer", category: "aspirantes", prayers: [] },
  { name: "Álvaro Díez de Mesa", category: "aspirantes", prayers: [] },

  // Familia
  { name: "Papá", category: "familia", prayers: [] },
  { name: "Mamá", category: "familia", prayers: [] },
  { name: "CARLOS", category: "familia", prayers: [] },
  { name: "Almu", category: "familia", prayers: [] },
  { name: "~María", category: "familia", prayers: [] },
  { name: "Jesús", category: "familia", prayers: [] },
  { name: "Ana", category: "familia", prayers: [] },
  { name: "Álvaro", category: "familia", prayers: [] },
  { name: "Miguel", category: "familia", prayers: [] },
  { name: "Pablo", category: "familia", prayers: [] },

  // SJ
  { name: "Arturo", category: "sj", prayers: [] },
  { name: "Carlos", category: "sj", prayers: [] },
  { name: "Ignacio Gómez", category: "sj", prayers: [] },

  // Pitables
  { name: "Fer Baiget", category: "pitables", prayers: [] },
  { name: "Carlos Alonso", category: "pitables", prayers: [] },
  { name: "Jaime Valcaneras", category: "pitables", prayers: [] },
  { name: "Paco Otero", category: "pitables", prayers: [] },
  { name: "Ignacio Gómez-Capapé", category: "pitables", prayers: [] },
  { name: "Pedro Izco", category: "pitables", prayers: [] },

  // Abuelos
  { name: "Abuelo Javier", category: "abuelos", prayers: [] },
  { name: "Abuela Luci", category: "abuelos", prayers: [] },
  { name: "Abuela Sole", category: "abuelos", prayers: [] },
  { name: "Abuelo Nino (RIP)", category: "abuelos", prayers: [] },
  { name: "Tía Leo", category: "abuelos", prayers: [] },
  { name: "Tía Pepi (RIP)", category: "abuelos", prayers: [] },
  { name: "Tía Encarna", category: "abuelos", prayers: [] },

  // SR
  { name: "Josemaria Colino", category: "sr", prayers: [] },
  { name: "Carlos Alonso", category: "sr", prayers: [] },
  { name: "Nico Mundet", category: "sr", prayers: [] },
  { name: "Borja Carmona", category: "sr", prayers: [] },
  { name: "Pablo Fernández", category: "sr", prayers: [] },
  { name: "Álvaro Juliá", category: "sr", prayers: [] },
  { name: "Jaime Sagardía", category: "sr", prayers: [] },
  { name: "Íñigo Valcaneras", category: "sr", prayers: [] },
  { name: "Íñigo Montoya", category: "sr", prayers: [] },
  { name: "Jaime Ocaña", category: "sr", prayers: [] },
  { name: "Rodrigo Salvadores", category: "sr", prayers: [] },
  { name: "Miguel Fuster", category: "sr", prayers: [] },
  { name: "Juan González", category: "sr", prayers: [] },

  // Amigos
  { name: "Arturo", category: "amigos", prayers: [
    { id: "arturo-1", text: "punto 99 surco - G", status: "active" }
  ] },
  { name: "Jorge López", category: "amigos", prayers: [] },
  { name: "Luís Herranz", category: "amigos", prayers: [] },
  { name: "Javi Mateo", category: "amigos", prayers: [] },
  { name: "Javi Lorenzo", category: "amigos", prayers: [] },
  { name: "Juan Lorenzo", category: "amigos", prayers: [] },
  { name: "Alvaro Del Riego", category: "amigos", prayers: [] },
  { name: "Gonzalo Alocén", category: "amigos", prayers: [] },
  { name: "Fernando Gutiérrez", category: "amigos", prayers: [] },
  { name: "Gabriel Uribe", category: "amigos", prayers: [] },
  { name: "JORGE SÁNCHEZ", category: "amigos", prayers: [] },
  { name: "Gonzalo Martín", category: "amigos", prayers: [] },
  { name: "David Caño", category: "amigos", prayers: [] },
  { name: "Pedro Salcedo", category: "amigos", prayers: [] },
  { name: "Javi Martín", category: "amigos", prayers: [] },
  { name: "Rafa Pastor", category: "amigos", prayers: [] },
  { name: "Juan Herranz", category: "amigos", prayers: [] },
  { name: "Teo Isern", category: "amigos", prayers: [] },
  { name: "Esther", category: "amigos", prayers: [] },
  { name: "Gonzalo", category: "amigos", prayers: [] },

  // UNAV
  { name: "Álvaro Ferrero", category: "unav", prayers: [] },
  { name: "Antonio Posa", category: "unav", prayers: [] },
  { name: "Fernando Páramo", category: "unav", prayers: [] },
  { name: "Sonso de Lucas", category: "unav", prayers: [] },
  { name: "Blanca Castrillón", category: "unav", prayers: [] },
  { name: "Matilde Govantes", category: "unav", prayers: [] },
  { name: "Miriam Martínez", category: "unav", prayers: [] },
  { name: "Marta Aldeguer", category: "unav", prayers: [] },
  { name: "María Apestegui", category: "unav", prayers: [] },
  { name: "Catalina Albesa (RIP)", category: "unav", prayers: [] },
  { name: "Carmen García", category: "unav", prayers: [] },
  { name: "Isabella Cardenal", category: "unav", prayers: [] },

  // Clase UAM
  { name: "Manuel Millán Ceña", category: "clase-uam", prayers: [] },
  { name: "Eduardo Franco Guardiola", category: "clase-uam", prayers: [] },
  { name: "Rubén Morales", category: "clase-uam", prayers: [] },
  { name: "Mauro Blas de Paz", category: "clase-uam", prayers: [] },
  { name: "Miguel Barderas", category: "clase-uam", prayers: [] },
  { name: "Daniel Ordóñez", category: "clase-uam", prayers: [] },
  { name: "Jesús Orive", category: "clase-uam", prayers: [] },
  { name: "Javier Marín", category: "clase-uam", prayers: [] },
  { name: "Diego Marín", category: "clase-uam", prayers: [] },

  // Novios
  { name: "Carlos y Leire", category: "novios", prayers: [] },
  { name: "Arturo y Gabriela", category: "novios", prayers: [] },
  { name: "Fer y Marta", category: "novios", prayers: [] },
  { name: "Jardón y Almu", category: "novios", prayers: [] },
  { name: "Alfonso y Rocío", category: "novios", prayers: [] },
  { name: "Sonso y Álvaro", category: "novios", prayers: [] },
  { name: "Blanca y Jose", category: "novios", prayers: [] },
  { name: "Miriam y Jorge", category: "novios", prayers: [] },
  { name: "Teo y Carlota", category: "novios", prayers: [] },
  { name: "Gabriel e Isa", category: "novios", prayers: [] },
  { name: "Pablo Cerezo y Bego de Irala", category: "novios", prayers: [] },
  { name: "Juliá y Ana", category: "novios", prayers: [] },
  { name: "Monto y Nuria Suevos", category: "novios", prayers: [] },
  { name: "Emilio y Blanca", category: "novios", prayers: [] },
  { name: "Fernando Páramo y Julia", category: "novios", prayers: [] },
  { name: "Jaime Sagardía y Camino", category: "novios", prayers: [] },

  // Europea
  { name: "Julen Ibáñez de Opacua Romo", category: "europea", prayers: [] },
  { name: "José Luís Chicharro Rico", category: "europea", prayers: [] },
  { name: "Mario de Andrés Martín", category: "europea", prayers: [] },
  { name: "Patricio Satrústegui", category: "europea", prayers: [] },
  { name: "Iván Serra Gifra", category: "europea", prayers: [] },
  { name: "Diego López Burrieza", category: "europea", prayers: [] },
  { name: "Iván Canora Álvarez", category: "europea", prayers: [] },

  // Gente Montalban
  { name: "Pablo Fortuño", category: "gente-montalban", prayers: [] },
  { name: "Diego Suárez", category: "gente-montalban", prayers: [] },
  { name: "Alfonso Moya", category: "gente-montalban", prayers: [] },
  { name: "Pisco", category: "gente-montalban", prayers: [] },
  { name: "Pablo Zaballa", category: "gente-montalban", prayers: [] },
  { name: "Pablo Angulo", category: "gente-montalban", prayers: [] },
  { name: "Rodrigo Ugarte", category: "gente-montalban", prayers: [] },
  { name: "Sergio Hallado", category: "gente-montalban", prayers: [] },
  { name: "Pablo Arias", category: "gente-montalban", prayers: [] },
  { name: "Jaime Nowack", category: "gente-montalban", prayers: [] },
  { name: "Jaime de Parias", category: "gente-montalban", prayers: [] },
  { name: "Juan Gayán", category: "gente-montalban", prayers: [] },
  { name: "Alejandro Ansó", category: "gente-montalban", prayers: [] },
  { name: "Vytautas", category: "gente-montalban", prayers: [] },
  { name: "Alfonso Jiménez", category: "gente-montalban", prayers: [] },
  { name: "Juan Pedro Galán", category: "gente-montalban", prayers: [] },
  { name: "Noé", category: "gente-montalban", prayers: [] },
  { name: "Ignacio de la Oliva", category: "gente-montalban", prayers: [] },

  // Primos
  { name: "MARCOS", category: "primos", prayers: [] },
  { name: "Javi", category: "primos", prayers: [] },
  { name: "Alberto", category: "primos", prayers: [] },
  { name: "Lucía", category: "primos", prayers: [] },
  { name: "Silvya", category: "primos", prayers: [] },
  { name: "Sara", category: "primos", prayers: [] },
  { name: "Rocío", category: "primos", prayers: [] },
  { name: "Carlos", category: "primos", prayers: [] },
  { name: "Celia", category: "primos", prayers: [] },
  { name: "Vega", category: "primos", prayers: [] },
  { name: "Richi", category: "primos", prayers: [] },
  { name: "Dani", category: "primos", prayers: [] },
  { name: "Aurora", category: "primos", prayers: [] },
  { name: "Valentina", category: "primos", prayers: [] },
  { name: "Esmeralda", category: "primos", prayers: [] },
  { name: "Carla", category: "primos", prayers: [] },
  { name: "Tía Sole", category: "primos", prayers: [] },
  { name: "Tío Jose", category: "primos", prayers: [] },
  { name: "Tío Nino", category: "primos", prayers: [] },
  { name: "Tía Pili", category: "primos", prayers: [] },
  { name: "Fuencis", category: "primos", prayers: [] },
  { name: "Nuri", category: "primos", prayers: [] },
  { name: "Mónica", category: "primos", prayers: [] },

  // Con los que he vivido
  { name: "D. Javier Elorduy (Montalbán)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Kike Barbero (Montalbán)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Mikel Mendía (Montalbán)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Juanma Ordóñez (Montalbán)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Nacho Tornel (Montalbán)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Pelayo López-Medel (Montalbán)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Rafa Gª De la Cruz (Montalbán)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Luís Gª- Menacho (Montalbán)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Jon Gandarias (Montalbán)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "D. Gabriel Fernández (Jara/MTBN)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Jaime Ugarte (Jara/MTBN)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "D. José Luís de Prada (Montalbán)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "D. Pablo González-Villalobos (Montalbán)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Ramón Palacios (Montalbán)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Gonzalo Halcón (Convivencia)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Iñigo Canosa (Convivencia)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Pablo Sagarra (Convivencia)", category: "con-los-que-he-vivido", prayers: [] },
  { name: "Jorge Ruiz (Convivencia)", category: "con-los-que-he-vivido", prayers: [] },

  // Jara
  { name: "Javier de la Rubia", category: "jara", prayers: [] },
  { name: "Jesús Milán", category: "jara", prayers: [] },
  { name: "Gonzalo Dusmet", category: "jara", prayers: [] },
  { name: "Javier Saavedra", category: "jara", prayers: [] },
  { name: "Mateo Garcia Masa", category: "jara", prayers: [] },
  { name: "Juan Coma", category: "jara", prayers: [] },
  { name: "D. Álvaro", category: "jara", prayers: [] },
  { name: "D. Borja", category: "jara", prayers: [] },
  { name: "Guille de Miguel", category: "jara", prayers: [] },
  { name: "Andrés Pampillón", category: "jara", prayers: [] },
  { name: "Xavi Mundet", category: "jara", prayers: [] },
  { name: "D. Javier Alfaro", category: "jara", prayers: [] },
  { name: "D. Jesús Vidal Gil", category: "jara", prayers: [] },
  { name: "Mizar (Centro)", category: "jara", prayers: [] },
  { name: "Montalbán (Centro)", category: "jara", prayers: [] },
  { name: "Jara (Centro)", category: "jara", prayers: [] },
  { name: "Codec (Centro)", category: "jara", prayers: [] }
];

export const INITIAL_MATTERS = [
  { title: "Las familias de CODEC", description: "Oración por las intenciones y dificultades de las familias de CODEC", category: "General", status: "active" }
];
